### ISSUE TITLE
Request for the complete code of single-stage algorithm about architecture_SDAmodal.py

### ISSUE THREAD

**Issue by HaoqianSong** [Championchess/Amodal-Completion-in-the-Wild#1]
Hello, does this project have a complete code base? Are both "architecture_OccAmodal.py" and "architecture_SDAmodal.py" based on "https://github.com/ducminhkhoi/Amodal-Instance-Seg-ASBU" for training and inference? Or "architecture_SDAmodal.py" is only based on "https://github.com/Tsingularity/dift" for training and inference. I saw that the single-stage prediction effect of "architecture_SDAmodal.py" is better. I really want to reproduce and apply this single-stage algorithm, but don’t know exactly how to proceed?

**Comment by RunpuWei** [comment]
The same problem, could you please provide a complete code, thank you!

**Comment by HaoqianSong** [comment]
There is an OSError: [Errno 101] Network is unreachable error when running extract_dift_amodal.py. Does this require downloading the relevant config.json online? Can you manually download the relevant config.json file? The relevant final error is as follows:


Traceback (most recent call last):
  File "/home/pcl/DETR/SDAseg/SDAseg/dift/extract_dift_amodal.py", line 67, in <module>
    ft = main(args)
  File "/home/pcl/DETR/SDAseg/SDAseg/dift/extract_dift_amodal.py", line 11, in main
    dift = SDFeaturizer(args.model_id)
  File "/home/pcl/DETR/SDAseg/SDAseg/dift/src/models/dift_sd.py", line 201, in __init__
    unet = MyUNet2DConditionModel.from_pretrained(sd_id, subfolder="unet")
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 472, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/pcl/anaconda3/envs/PY310/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-diffusion-2-1 does not appear to have a file named config.json.

**Comment by Championchess** [comment]
Hi, have you followed the instructions to clone the GitHub https://github.com/Tsingularity/dift/tree/main and do the replacement for the code?

**Comment by HaoqianSong** [comment]
Yes, I replaced the relevant code, and similar problems occurred when I reproduced the Demo of DIFT. May need to visit https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/unet/config.json online download or ask price, but conda cannot get to this file, I am looking at the local download access location of this file for local access.

**Comment by Championchess** [comment]
My code seems to download the SD weights automatically for me when I run the dift code. Have you installed the environment following their instructions?

**Comment by HaoqianSong** [comment]
Thank you for your reply, but I have solved the problem and forgot to tell you here. The problem is that diffusers needs to download a larger dependency file. I have downloaded and saved it manually. There are many similar problems like this in the diffusers project.

**Comment by typist2001** [comment]
您好，我碰到了同样的问题，请问单阶段模型SDAmodal的训练代码您复现出来了吗

**Comment by Championchess** [comment]
Please use the inference code with the pre-trained model to reproduce the results. It achieves 90.7 mIOU on COCOA test.
