### ISSUE TITLE
What are the steps of visualization

### ISSUE THREAD

**Issue by cc180326** [Championchess/Amodal-Completion-in-the-Wild#3]
What are the steps of visualization pls

**Comment by Championchess** [comment]
Please get the SD features first, and then run the inference to get the amodal mask predictions, and then you can visualise the masks.

**Comment by cc180326** [comment]
> Please get the SD features first, and then run the inference to get the amodal mask predictions, and then you can visualise the masks.

really thank u for reply  i will try .^^

**Comment by Championchess** [comment]
Thanks for your interest in the series of amodal works. Please refer to the concurrent work section in README.md for other contemporary works. If you would also want to get the completed content (appearance) of the occluded object, you can also apply https://github.com/cvlab-columbia/pix2gestalt.

**Comment by Championchess** [comment]
> What are the steps of visualization pls

The place to visualise the masks is in tools/test.py before Line 151 where the union between GT and Pred is calculated
