### ISSUE TITLE
Your ckpt link is fake link

### ISSUE THREAD

**Issue by 591582523h** [Championchess/Amodal-Completion-in-the-Wild#6]
Hello, could you provide a new ckpt link? I can't download the true ckpt from your link in the README.md

**Comment by 591582523h** [comment]
Sorry, I make a mistake in load ckpt because that my firstly load a ".tar" ckpt. We can straightly torch.load(".tar").

**Comment by JaeLee18** [comment]
Hello, how did you load the ckpt model from the tar file?
